### ISSUE TITLE
components in autocomplete(predictions_by_input) missing

### ISSUE THREAD

**Issue by PaulDaviesC** [marceldegraaf/google_places#71]
The original API have facility for searching for cities in a specific country by passing the parameter "types=(cities)&components=country:in". I did not find such a facility in this gem.

**Comment by marceldegraaf** [comment]
Thanks for pointing that out @PaulDaviesC. I don't currently have the time to add this feature myself, but a PR for this would be welcome.

**Comment by PaulDaviesC** [comment]
@marceldegraaf Yeah I will :)

**Comment by Faisal-nfl** [comment]
any one added components yet?
